### PR TITLE
docs: create Sprint 1 folder, Add meeting notes

### PR DESCRIPTION
**Pull request by Niravanaa**
### 🛠 Proposed Changes:

This pull request adds the sprint 1 document deliverable folder, and adds notes about the meetings that SvelteState has held so far.

### 📝 Details:

- The Sprint 1 folder is created
- The Sprint 1 folder now holds information regarding the four meetings held by SvelteState during Sprint 1

### CODE REVIEW

**Review by NathanGrenier — COMMENTED** [review]
Not sure if we can do this, but maybe put the `sprint 1` folders inside another folder named `deliverables` or `sprint-deliverables`. Would make the root a little less cluttered (we're eventually going to have 4 of these sprint folders).

**Comment by CarciDev** [comment]
> Not sure if we can do this, but maybe put the `sprint 1` folders inside another folder named `deliverables` or `sprint-deliverables`. Would make the root a little less cluttered (we're eventually going to have 4 of these sprint folders).

It is a good idea, but we need to ask the prof to avoid loosing points.

**Comment by NathanGrenier** [comment]
> It is a good idea, but we need to ask the prof to avoid loosing points.

Do you think he's not smart enough to find the folder named `deliverables`?

**Comment by CarciDev** [comment]
> > It is a good idea, but we need to ask the prof to avoid loosing points.
> 
> Do you think he's not smart enough to find the folder named `deliverables`?

The assumption is to assume worst case. He might be using a script to extract everyone's repository. He has a tendency to do that so far for anything we have submitted, such as the team name structure and stuff.

**Comment by NathanGrenier** [comment]
> The assumption is to assume worst case. He might be using a script to extract everyone's repository. He has a tendency to do that so far for anything we have submitted, such as the team name structure and stuff.

Sure. Did he say to name it exactly `Sprint 1`, or is it `sprint1` or some other variation?

**Review by CarciDev — APPROVED** [review]
Good stuff Nirav:)

**Pull request merged**
