### PR TITLE
Swap Vercel Blob for S3

### PR DESCRIPTION
**Pull request by briantkatch**
### 🛠 Proposed Changes:

Ran out of bandwidth on Vercel free. People were depending on @vercel/blob in several places so I stubbed it in a lib file to communicate with S3.

Everyone should test their upload-related feature in the preview environment. I gave the AWS secrets to Nathan

### CODE REVIEW

**Comment by briantkatch** [comment]
@NathanGrenier deploy failed due to Neon error, is that a compute limit you mentioned that is resetting soon?

**Comment by NathanGrenier** [comment]
> @NathanGrenier deploy failed due to Neon error, is that a compute limit you mentioned that is resetting soon?

Ya, should reset on April 1st or 2nd.

**Comment by briantkatch** [comment]
Checks passing with Neon back online, so test your features ig @CarciDev

**Review by Niravanaa — APPROVED** [review]
LGTM

**Pull request merged**
